services:
  db:
    image: postgres:17
    container_name: lounge-db
    environment:
      POSTGRES_DB: iulianlounge
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - lounge-data:/var/lib/postgresql/data

volumes:
  lounge-data:
